language: cpp
os: windows

env:
 - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
 
before_script:
 # - refreshenv
 # - unset -v _JAVA_OPTIONS
 # - git config --system core.longpaths true
 # - git clone --depth 1 https://github.com/TravaOpenJDK/openjdk-build.git
 #

script: 
 - choco install cygwin
 - ls /
 # - C:\\ProgramData\\chocolatey\\bin\\Cygwin.exe
 - ls C:\\tools\\cygwin
 - C:\\tools\\cygwin\\bin\\make --version
