language: cpp
os: windows

env:
 - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
 
before_script:
 - unset -v _JAVA_OPTIONS
 - git config --system core.longpaths true
 - git config --global core.autocrlf false
 - git clone --depth 1 https://github.com/TravaOpenJDK/openjdk-build.git
 
script: 
 - choco install cygwin
 - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip
 #- powershell -Command "C:\tools\cygwin\bin\bash.exe -c 'echo hello'"
 #- git config --system core.eol lf
 - powershell -Command "C:\tools\cygwin\bin\bash.exe -c './run.sh'" 
 
 
#- C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,bash
# - export LIBRARY_PATH="/c/tools/cygwin/bin"
# - export LD_LIBRARY_PATH="/c/tools/cygwin/bin"
# - export PATH=/c/tools/cygwin/bin
# - C:\\tools\\cygwin\\bin\\sh -c "echo hello"
# - C:\\tools\\cygwin\\bin\\sh -c "cat run.sh"
# - C:\\tools\\cygwin\\bin\\sh -c "/c/Users/travis/build/edudant/windows-travis-build/run.sh"
# - C:\\tools\\cygwin\\bin\\sh -c "make --version"
# - C:\\tools\\cygwin\\bin\\sh /c/Users/travis/build/edudant/windows-travis-build/run.sh
 # - choco install cyg-get
 # - cyg-get make
 # - ls /
 # - C:\\ProgramData\\chocolatey\\bin\\Cygwin.exe
